apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra
  labels:
    app: cassandra
  namespace: backend
spec:
  selector:
    matchLabels:
      app: cassandra
  storageClassName: fast
  resources:
    requests:
      storage: 1Gi
  accessModes: [ "ReadWriteOnce" ]