apiVersion: v1
kind: ConfigMap
metadata:
  name: ready-probe
  labels:
    app: cassandra
  namespace: backend
data:
  ready-probe.sh: |
    #!/bin/bash

    if [[ $(nodetool status | grep $POD_IP) == *"UN"* ]]; then
      echo "UN"
    else
      echo "Not Up"
      exit 1
    fi
