apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  labels:
    app: cassandra
  namespace: backend
spec:
  serviceName: cassandra
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      # terminationGracePeriodSeconds: 60
      containers:
        - name: cassandra
          image: cassandra:4.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          env:
            - name: MAX_HEAP_SIZE
              valueFrom:
                configMapKeyRef:
                  name: cassandra
                  key: MAX_HEAP_SIZE
            - name: HEAP_NEWSIZE
              valueFrom:
                configMapKeyRef:
                  name: cassandra
                  key: HEAP_NEWSIZE
            - name: JVM_OPTS
              valueFrom:
                configMapKeyRef:
                  name: cassandra
                  key: JVM_OPTS
            - name: MALLOC_ARENA_MAX
              valueFrom:
                configMapKeyRef:
                  name: cassandra
                  key: MALLOC_ARENA_MAX
            - name: CASSANDRA_SEEDS
              valueFrom:
                configMapKeyRef:
                  name: cassandra
                  key: CASSANDRA_SEEDS
            - name: CASSANDRA_CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: cassandra
                  key: CASSANDRA_CLUSTER_NAME
            - name: CASSANDRA_DC
              valueFrom:
                configMapKeyRef:
                  name: cassandra
                  key: CASSANDRA_DC
            - name: CASSANDRA_RACK
              valueFrom:
                configMapKeyRef:
                  name: cassandra
                  key: CASSANDRA_RACK
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: data
              mountPath: /opt/cassandra/data
            - name: logs
              mountPath: /opt/cassandra/logs
            - name: ready-probe
              mountPath: /ready-probe.sh
              subPath: ready-probe.sh
              readOnly: true
            - name: env
              mountPath: /env.sh
              subPath: env.sh
              readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 6Gi
            requests:
              cpu: 250m
              memory: 3Gi
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - ./env.sh
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - nodetool drain
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /ready-probe.sh
            initialDelaySeconds: 120
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 30
            failureThreshold: 5
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          stdin: true
      volumes:
        - name: ready-probe
          configMap:
            name: ready-probe
            defaultMode: 0777
        - name: env
          configMap:
            name: env
            defaultMode: 0777
      serviceAccountName: cassandra
      automountServiceAccountToken: true
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: backend
        labels:
          app: cassandra
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: fast
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: logs
        namespace: backend
        labels:
          app: cassandra
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 512Mi

