apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: backend
spec:
  selector:
    matchLabels:
      app: grafana
  resources:
    requests:
      storage: 1Gi
  accessModes: [ "ReadWriteOnce" ]
