apiVersion: v1
kind: Service
metadata:
  name:  grafana
  labels:
    app: grafana
  namespace: backend
spec:
  selector:
    app: grafana
  type: LoadBalancer
  sessionAffinity: None
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP