apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter
  labels:
    app: jupyter
  namespace: backend
spec:
  selector:
    matchLabels:
      app: jupyter
  resources:
    requests:
      storage: 1Gi
  accessModes: [ "ReadWriteOnce" ]
