apiVersion: v1
kind: Service
metadata:
  name:  kairosdb
  labels:
    app: kairosdb
  namespace: backend
spec:
  selector:
    app:  kairosdb
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP