apiVersion: v1
kind: Service
metadata:
  name:  kairosdb
  labels:
    app: kairosdb
  namespace: backend
spec:
  selector:
    app:  kairosdb
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP