version: "3.9"
services:
  hundi:
    image: hundi:local
    build:
      context: .
      target: development
    env_file:
      - ../.hundi.env
      # - ../.kairosdb.env
    healthcheck:
      test: [ "CMD", "cli.py", "--info healthcheck" ]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 40s
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/app/:delegated
      # - ../home:/home/app/:delegated
