version: "3.9"
services:
  hundi:
    image: python/python:3.10.0-slim-buster
    build:
      context: .
      target: development
    enviroment:
      - KAIROSDB_URL=http://localhost:8080
      - KAIROSDB_API_DATAPOINTS=/api/v1/datapoints
    healthcheck:
      test: ["CMD", "cli.py", "--info healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - ./:/app/:delegated