apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels: 
    app: jupyter
  namespace: frontend
spec:
  type: NodePort
  selector:
    app: jupyter
  ports:
    - protocol: TCP
      nodePort: 30040
      port: 8888
      targetPort: 8888