apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  labels:
    app: jupyter
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - name: jupyter
          image: jupyter/minimal-notebook:latest
          ports:
            - containerPort: 8888
          # command: [ "start-notebook.sh" ]
          # args: [ "--NotebookApp.token=''" ]
          resources:
            limits:
              cpu: 125m
              memory: 1Gi
            requests:
              cpu: 62m
              memory: 512Mi