apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels: 
    app: jupyter
  namespace: backend
spec:
  type: LoadBalancer
  selector:
    app: jupyter
  ports:
    - name: http
      protocol: TCP
      nodePort: 30040
      port: 8888
      targetPort: http