apiVersion: apps/v1
kind: Deployment
metadata:
  name: kariosdb
  labels:
    app: kairosdb
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kairosdb
  template:
    metadata:
      labels:
        app: kairosdb
    spec:
      # initContainers:
      #   - name: wait
      #     image: rcosnita/wait-container:1.0.0
      #     imagePullPolicy: IfNotPresent
      #     args: [ "/etc/config/config.json" ]
      #     volumeMounts:
      #       - name: wait
      #         mountPath: /etc/config
      containers:
        - name: kairosdb
          image: rcosnita/kairosdb:1.3.0-3283c4e8d4d # this must be changed when we onboard kairosdb to official dockerhub repository.
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c" ]
          args:
            - "cp -f /etc/kairosdb/custom-configs/*.conf /etc/kairosdb && . ~/.bashrc && kairosdb.sh run"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: CASSANDRA_USER
              valueFrom:
                secretKeyRef:
                  name: cassandra
                  key: CASSANDRA_USER
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra
                  key: CASSANDRA_PASSWORD
          volumeMounts:
            - name: config
              mountPath: /etc/kairosdb/custom-configs
          resources:
            limits:
              cpu: 250m
              memory: 2Gi
            requests:
              cpu: 125m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 15
            failureThreshold: 5
          stdin: true
      volumes:
        # - name: wait
        #   configMap:
        #     name: wait
        - name: config
          configMap:
            name: kairosdb
            items:
            - key: kairosdb.conf
              path: kairosdb.conf
      serviceAccountName: kairosdb
      automountServiceAccountToken: true
            
