hundi-venv-bootstrap:
	virtualenv -p `which python3.9` venv
	venv/bin/python -m pip install --upgrade pip

# hundi-venv-activate:
# 	source venv/bin/activate

# hundi-venv-deactivate:
# 	deactivate
# 	rm -r venv

hundi-vscode-bootstrap:
	mkdir ../../.vscode
	cp .vscode.settings.json ../../.vscode/settings.json